services:
  - postgresql
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle install
script:
  - bundle exec rspec
