development:
  adapter: postgresql
  encoding: unicode
  database: blog
  pool: 5
  username: abhishek
  password:
  timeout: 5000
test:
  adapter: postgresql
  database: travis_ci_test
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] %> 
  database: <%= ENV['DATABASE_NAME'] %> 
  username: <%= ENV['DATABASE_USER'] %> 
  password: <%= ENV['DATABASE_PASSWORD'] %> 
